ddp:
  master_addr: "localhost"
  master_port: "29500"
  num_devices: 1

rlbench:
  task_name: 'move_above'
  tasks: [move_above]
  demos: 64
  demo_path: /home/user/School/peract_l2r/data_above
  episode_length: 25
  cameras: [front, left_shoulder, right_shoulder, wrist]
  # cameras: [front]
  camera_resolution: [128, 128]
  scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
  include_lang_goal_in_obs: True

replay:
  batch_size: 4
  timesteps: 1
  prioritisation: False
  task_uniform: True
  use_disk: True
  path: '/tmp/peract/replay'
  max_parallel_processes: 32

framework:
  log_freq: 50
  save_freq: 1000
  tensorboard_logging: False
  csv_logging: True
  training_iterations: 40000
  logdir: '/home/user/School/peract_l2r/logs/height'
  logging_level: 20 # https://docs.python.org/3/library/logging.html#levels
  seeds: 1
  start_seed: 0
  load_existing_weights: False
  num_weights_to_keep: 60 # older checkpoints will be deleted chronologically
  num_workers: 0

defaults:
  - method: PERACT_BC

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task_name}/${method.name}