ddp:
  master_addr: "localhost"
  master_port: "29502"
  visualize_port: "29501"
  num_devices: 1

rlbench:
  # task_name: 'pick_up'
  # tasks: [pick_up]
  # task_name: 'move_front'
  # tasks: [move_front]
  task_name: 'multi'
  # task_name: 'open_drawer_motions'
  tasks: [open_drawer_motions, slide_block_motions, sweep_to_dustpan_motions, 
          meat_off_grill_motions, turn_tap_motions, put_item_in_drawer_motions,
          close_jar_motions, reach_and_drag_motions, stack_blocks_motions,
          light_bulb_in_motions, put_money_in_safe_motions, place_wine_at_rack_motions,
          put_groceries_in_cupboard_motions, place_shape_motions, push_buttons_motions,
          insert_onto_square_peg_motions, stack_cups_motions, place_cups_motions]
  demos: [100, 100, 100, 
          100, 100, 100, 
          100, 100, 100, 
          100, 100, 100,
          100, 100, 100, 
          100, 100, 100]
  # tasks: [open_drawer_motions, slide_block_motions]
  # demos: [16, 16]
  demo_path: /home/user/School/peract_l2r/data
  episode_length: 600
  cameras: [front, left_shoulder, right_shoulder, wrist]
  # cameras: [front]
  camera_resolution: [128, 128]
  # scene_bounds: [-0.3, -0.5, 0.8, 0.7, 0.5, 1.8]
  scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
  include_lang_goal_in_obs: True
  fine_tune_tasks: [open_drawer, slide_block, sweep_to_dustpan,
                    meat_off_grill, turn_tap, put_item_in_drawer,
                    close_jar, reach_and_drag, stack_blocks,
                    light_bulb_in, put_money_in_safe, place_wine_at_rack,
                    put_groceries_in_cupboard, push_buttons, 
                    stack_cups, place_cups]
  fine_tune_demos: [2, 2, 2, 
                    2, 2, 2, 
                    2, 2, 2, 
                    2, 2, 2,
                    2, 2,
                    2, 2]
  # fine_tune_tasks: [open_drawer, slide_block]
  # fine_tune_demos: [2, 2]

replay:
  batch_size: 4
  timesteps: 1
  prioritisation: False
  task_uniform: True
  use_disk: True
  path: '/tmp/peract/replay'
  max_parallel_processes: 32

framework:
  gpu: 1
  log_freq: 100
  # save_freq: 5000
  save_freq: 1000
  tensorboard_logging: False
  csv_logging: True
  # training_iterations: 200001
  training_iterations: 20001
  logdir: '/home/user/School/peract_l2r/logs/fine_tune_1'
  use_start_weight: True
  start_weight: '/home/user/School/peract_l2r/logs/multi_motions_8/multi/PERACT_BC/seed0/weights/200000'
  logging_level: 20 # https://docs.python.org/3/library/logging.html#levels
  seeds: 1
  start_seed: 0
  load_existing_weights: False
  num_weights_to_keep: 60 # older checkpoints will be deleted chronologically
  num_workers: 0

defaults:
  - method: PERACT_BC

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task_name}/${method.name}