ddp:
  master_addr: "localhost"
  master_port: "29502"
  visualize_port: "29501"
  num_devices: 1

rlbench:
  # task_name: 'put_money_in_safe_motions'
  # tasks: [put_money_in_safe_motions]
  # task_name: 'move_front'
  tasks: [open_drawer_motions, push_buttons_motions]
  # tasks: [sweep_real]
  task_name: 'multi'
  # task_name: 'open_drawer_motions'
  # tasks: [open_drawer_motions, slide_block_motions, sweep_to_dustpan_motions, 
  #         meat_off_grill_motions, turn_tap_motions, put_item_in_drawer_motions,
  #         close_jar_motions, reach_and_drag_motions, stack_blocks_motions,
  #         put_money_in_safe_motions, place_wine_at_rack_motions,
  #         put_groceries_in_cupboard_motions, push_buttons_motions,
  #         stack_cups_motions]
  # demos: [100, 100, 100, 
  #         100, 100, 100, 
  #         100, 100, 100, 
  #         100, 100,
  #         100, 100, 
  #         100]
  demos: [10, 10]
  # tasks: [open_drawer, slide_block_to_color_target, sweep_to_dustpan_of_size,
  #         meat_off_grill, turn_tap, put_item_in_drawer_lv2,
  #         close_jar, reach_and_drag, stack_blocks_lv2,
  #         put_money_in_safe, place_wine_at_rack_location,
  #         put_groceries_in_cupboard, push_buttons, 
  #         stack_cups_lv2]
  # demos: [10, 10, 10, 
  #         10, 10, 10, 
  #         10, 10, 10, 
  #         10, 10,
  #         10, 10, 
  #         10]
  # tasks: [meat_off_grill]
  # demos: [10]
  # tasks: [open_drawer_motions, slide_block_motions]
  # demos: [1]
  demo_path: /home/carl/School/talk-through-it/data
  episode_length: 900
  cameras: [front, left_shoulder, right_shoulder, wrist]
  # cameras: [overhead]
  # camera_resolution: [640, 480]
  camera_resolution: [128,128]
  # scene_bounds: [-0.3, -0.5, 0.8, 0.7, 0.5, 1.8]
  scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
  include_lang_goal_in_obs: True

  # fine_tune_tasks: [meat_off_grill]
  # fine_tune_demos: [10]
  fine_tune_tasks2: [open_drawer, slide_block, sweep_to_dustpan,
                    meat_off_grill, turn_tap, put_item_in_drawer_lv2,
                    close_jar, reach_and_drag, stack_blocks_lv2,
                    put_money_in_safe, place_wine_at_rack,
                    put_groceries_in_cupboard, push_buttons, 
                    stack_cups_lv2]
  fine_tune_demos2: [10, 10, 10,
                    10, 10, 10,
                    10, 10, 10,
                    10, 10,
                    10, 10,
                    10]
  fine_tune_tasks3: [put_item_in_drawer_lv3, stack_blocks_lv3, push_buttons_lv3, stack_cups_lv3]
  fine_tune_demos3: [10, 10, 10, 10]
  # fine_tune_demos: [2, 2, 2, 
  #                   2, 2, 2, 
  #                   2, 2, 2, 
  #                   2, 2,
  #                   2, 2,
  #                   2]
  # fine_tune_demos: [5, 5, 5,
  #                   5, 5, 5,
  #                   5, 5, 5,
  #                   5, 5,
  #                   5, 5,
  #                   5]
  lang_variations: [0]

replay:
  batch_size: 4
  timesteps: 1
  prioritisation: False
  task_uniform: True
  use_disk: True
  path: '/tmp/peract/replay'
  max_parallel_processes: 12

framework:
  gpu: 0
  log_freq: 100
  # save_freq: 5000
  save_freq: 5000
  tensorboard_logging: False
  csv_logging: True
  training_iterations: 100001
  # training_iterations: 50001
  logdir: '/home/carl/School/talk-through-it/logs/quickstart'
  use_start_weight: False
  # start_weight: '/home/user/School/peract_l2r/logs/fine_tune_6/multi/PERACT_BC/seed0/weights/95000'
  start_weight: /home/user/School/peract_l2r/logs/lv1_to_lv2_10_demos/multi/PERACT_BC/seed2/weights/75000
  logging_level: 20 # https://docs.python.org/3/library/logging.html#levels
  seeds: 1
  start_seed: 0
  load_existing_weights: False
  num_weights_to_keep: 60 # older checkpoints will be deleted chronologically
  num_workers: 0

defaults:
  - method: PERACT_BC

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task_name}/${method.name}