ddp:
  master_addr: "localhost"
  master_port: "29502"
  visualize_port: "29501"
  num_devices: 1

rlbench:
  # task_name: 'pick_up'
  # tasks: [pick_up]
  # task_name: 'move_front'
  # tasks: [move_front]
  task_name: 'multi'
  # task_name: 'open_drawer_motions'
  tasks: [open_drawer_motions, slide_block_motions, sweep_to_dustpan_motions, 
          meat_off_grill_motions, turn_tap_motions, put_in_drawer_motions]
  demos: [64, 64, 100, 100, 100, 100]
  demo_path: /home/user/School/peract_l2r/data
  episode_length: 100
  cameras: [front, left_shoulder, right_shoulder, wrist]
  # cameras: [front]
  camera_resolution: [128, 128]
  # scene_bounds: [-0.3, -0.5, 0.8, 0.7, 0.5, 1.8]
  scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
  include_lang_goal_in_obs: True
  # fine_tune_tasks: ['kitchen_open_fridge', 'kitchen_move_above', 'kitchen_move_front']
  # fine_tune_demos: [1, 64, 64]
  # fine_tune_weight: 66000

replay:
  batch_size: 4
  timesteps: 1
  prioritisation: False
  task_uniform: True
  use_disk: True
  path: '/tmp/peract/replay'
  max_parallel_processes: 32

framework:
  gpu: 1
  log_freq: 100
  save_freq: 2000
  tensorboard_logging: False
  csv_logging: True
  training_iterations: 100001
  logdir: '/home/user/School/peract_l2r/logs/multi_motions_2'
  use_start_weight: False
  start_weight: '/home/user/School/peract_l2r/logs/open_drawer_motions/open_drawer_motions/PERACT_BC/seed0/weights/82000'
  logging_level: 20 # https://docs.python.org/3/library/logging.html#levels
  seeds: 1
  start_seed: 0
  load_existing_weights: False
  num_weights_to_keep: 60 # older checkpoints will be deleted chronologically
  num_workers: 0

defaults:
  - method: PERACT_BC

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task_name}/${method.name}