ddp:
  master_addr: "localhost"
  master_port: "29500"
  visualize_port: "29501"
  num_devices: 1

rlbench:
  # task_name: 'pick_up'
  # tasks: [pick_up]
  # task_name: 'move_front'
  # tasks: [move_front]
  task_name: 'multi'
  tasks: [kitchen_move_above, kitchen_move_front]
  demos: 64
  demo_path: /home/user/School/peract_l2r/data
  episode_length: 100
  cameras: [overhead, left_shoulder, right_shoulder, wrist]
  # cameras: [front]
  camera_resolution: [128, 128]
  scene_bounds: [-0.3, -0.5, 0.8, 0.7, 0.5, 1.8]
  include_lang_goal_in_obs: True
  fine_tune_tasks: ['kitchen_open_fridge', 'kitchen_move_above', 'kitchen_move_front']
  fine_tune_demos: [1, 64, 64]
  fine_tune_weight: 66000

replay:
  batch_size: 4
  timesteps: 1
  prioritisation: False
  task_uniform: True
  use_disk: True
  path: '/tmp/peract/replay'
  max_parallel_processes: 32

framework:
  log_freq: 100
  save_freq: 2000
  tensorboard_logging: False
  csv_logging: True
  training_iterations: 100001
  logdir: '/home/user/School/peract_l2r/logs/multi_model_1_2'
  logging_level: 20 # https://docs.python.org/3/library/logging.html#levels
  seeds: 1
  start_seed: 0
  load_existing_weights: False
  num_weights_to_keep: 60 # older checkpoints will be deleted chronologically
  num_workers: 0

defaults:
  - method: PERACT_BC

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task_name}/${method.name}